import type { AgentDashboardData } from './types'

export const fallbackAgentDashboardData: AgentDashboardData = {
  agent: {
    name: 'Agent',
    brokerage: 'Your brokerage',
    market: 'Dubai agent desk',
    lastUpdated: 'just now',
  },
  summary: {
    openTasks: 14,
    qualifiedBuyers: 9,
    viewingsToday: 4,
    offersAtRisk: 2,
    openEscalations: 3,
  },
  performance: {
    scope: 'current_agent',
    agentUserId: null,
    generatedAt: null,
    primary: {
      key: 'today',
      label: 'Today',
      metrics: {
        newBuyerConversations: 3,
        escalationsHandled: 1,
        avgResponseMinutes: 12,
        followUpsSent: 4,
        viewingsProposed: 2,
        viewingsConfirmed: 1,
        viewingsCompleted: 1,
        offersDetected: 1,
        hotLeadsActive: 5,
        tasksOverdue: 0,
      },
    },
    windows: [
      {
        key: 'today',
        label: 'Today',
        metrics: {
          newBuyerConversations: 3,
          escalationsHandled: 1,
          avgResponseMinutes: 12,
          followUpsSent: 4,
          viewingsProposed: 2,
          viewingsConfirmed: 1,
          viewingsCompleted: 1,
          offersDetected: 1,
          hotLeadsActive: 5,
          tasksOverdue: 0,
        },
      },
      {
        key: '7d',
        label: '7 days',
        metrics: {
          newBuyerConversations: 18,
          escalationsHandled: 7,
          avgResponseMinutes: 16,
          followUpsSent: 21,
          viewingsProposed: 9,
          viewingsConfirmed: 6,
          viewingsCompleted: 4,
          offersDetected: 3,
          hotLeadsActive: 12,
          tasksOverdue: 2,
        },
      },
      {
        key: '30d',
        label: '30 days',
        metrics: {
          newBuyerConversations: 63,
          escalationsHandled: 19,
          avgResponseMinutes: 18,
          followUpsSent: 74,
          viewingsProposed: 28,
          viewingsConfirmed: 17,
          viewingsCompleted: 11,
          offersDetected: 8,
          hotLeadsActive: 20,
          tasksOverdue: 4,
        },
      },
    ],
  },
  morningQueue: [
    {
      id: 'queue-1',
      priority: 'critical',
      title: 'Offer expires before lunch',
      context: 'Buyer is at AED 3.42M on Downtown 2BR. Seller asked for a clean answer by 12:00.',
      buyerName: 'Karim A.',
      listingName: 'Act One Act Two · 2BR',
      nextAction: 'Call seller with counter range',
      due: '09:30',
    },
    {
      id: 'queue-2',
      priority: 'high',
      title: 'Viewing-ready family needs slots',
      context: 'Budget and community preference match the Springs townhouse campaign.',
      buyerName: 'Neha S.',
      listingName: 'Springs 8 · Type 3M',
      nextAction: 'Send two evening viewing options',
      due: '10:15',
    },
    {
      id: 'queue-3',
      priority: 'high',
      title: 'Mortgage buyer waiting on NOC timing',
      context: 'Buyer asked whether transfer can complete before school term planning.',
      buyerName: 'Omar R.',
      listingName: 'Dubai Hills Estate · 3BR',
      nextAction: 'Confirm timeline with conveyancing',
      due: '11:00',
    },
    {
      id: 'queue-4',
      priority: 'normal',
      title: 'Refresh stale WhatsApp draft',
      context: 'Dalya prepared a follow-up after the buyer compared two Palm Jumeirah units.',
      buyerName: 'Elena P.',
      listingName: 'Marina Residences · 2BR',
      nextAction: 'Review and send buyer summary',
      due: '13:45',
    },
  ],
  conversationInbox: [
    {
      id: 'sample-conv-1',
      buyerName: 'Ahmed K.',
      buyerPhone: '+971502148821',
      listingName: 'Downtown resale apartment',
      unitNumber: '2BR',
      summary: 'Budget fit, asked for evening viewing slots.',
      nextStep: 'Call now and confirm two viewing options.',
      lastMessage: 'Can I see it after 6 today?',
      lastSeen: '18 min ago',
      messageCount: 6,
      offerCount: 0,
      openEscalationCount: 1,
      interestLevel: 'high',
    },
  ],
  escalationInbox: [
    {
      id: 'esc-1',
      token: 'DXB42A8K',
      category: 'offer',
      state: 'open',
      urgency: 'critical',
      buyerName: 'Faisal Al N.',
      buyerPhone: '+971501112233',
      listingName: 'Downtown 2BR resale',
      unitNumber: '1204',
      latestQuestion: 'Can the seller review AED 3.42M today?',
      questionCount: 1,
      openedAt: '09:12',
      lastBuyerMessageAt: '09:12',
      routeExpiresAt: 'Tomorrow',
      questions: [
        {
          id: 'esc-q-1',
          text: 'Can the seller review AED 3.42M today?',
          addedAt: '09:12',
        },
      ],
    },
    {
      id: 'esc-2',
      token: 'NOC91B2D',
      category: 'regulatory_documents',
      state: 'updated',
      urgency: 'high',
      buyerName: 'Omar R.',
      buyerPhone: '+971504445566',
      listingName: 'Dubai Hills Estate 3BR',
      unitNumber: 'TH-18',
      latestQuestion: 'Can you confirm if the NOC is already available?',
      questionCount: 2,
      openedAt: '08:48',
      lastBuyerMessageAt: '09:04',
      routeExpiresAt: 'Tomorrow',
      questions: [
        {
          id: 'esc-q-2',
          text: 'Can transfer complete before school term planning?',
          addedAt: '08:48',
        },
        {
          id: 'esc-q-3',
          text: 'Can you confirm if the NOC is already available?',
          addedAt: '09:04',
        },
      ],
    },
  ],
  campaignSnapshot: {
    headline: 'Villa exit campaign is producing the strongest qualified buyer flow.',
    activeCampaigns: 5,
    newLeads: 38,
    qualifiedLeads: 11,
    responseRate: '42%',
    costPerQualifiedLead: 'AED 318',
    campaigns: [
      {
        id: 'campaign-1',
        name: 'Dubai Hills family villas',
        audience: 'AED 7M-10M end users',
        status: 'live',
        spend: 'AED 3,480',
        leads: 19,
        qualified: 7,
        insight: 'Best replies mention school commute and handover certainty.',
      },
      {
        id: 'campaign-2',
        name: 'Downtown below-market resales',
        audience: 'Cash buyers and investors',
        status: 'needs_action',
        spend: 'AED 1,920',
        leads: 12,
        qualified: 3,
        insight: 'Creative fatigue detected after three low-intent price-check threads.',
      },
      {
        id: 'campaign-3',
        name: 'Palm branded residences',
        audience: 'Western expat relocators',
        status: 'warming',
        spend: 'AED 980',
        leads: 7,
        qualified: 1,
        insight: 'Traffic quality improving, but buyers need clearer service-charge context.',
      },
    ],
  },
  overnightBuyerDigest: [
    {
      id: 'buyer-1',
      buyerName: 'Sarah M.',
      intent: 'viewing_ready',
      message: 'Asked for a same-day viewing after confirming the unit is vacant on transfer.',
      budget: 'AED 5.8M cash',
      target: 'Dubai Hills 3BR villa',
      recommendedAction: 'Call before 09:15 and hold the 18:30 slot',
      lastSeen: '02:18',
    },
    {
      id: 'buyer-2',
      buyerName: 'Faisal Al N.',
      intent: 'offer_ready',
      message: 'Requested seller acceptance range and said funds are already local.',
      budget: 'AED 3.4M-3.5M',
      target: 'Downtown 2BR resale',
      recommendedAction: 'Share strongest comparable and invite a written offer',
      lastSeen: '00:41',
    },
    {
      id: 'buyer-3',
      buyerName: 'Ankit B.',
      intent: 'financing',
      message: 'Needs payment-plan clarity before booking a viewing with spouse.',
      budget: 'AED 2.9M mortgage',
      target: 'Creek Harbour 2BR',
      recommendedAction: 'Send financing checklist and ask for pre-approval status',
      lastSeen: '23:57',
    },
  ],
  todaysViewings: [
    {
      id: 'viewing-1',
      time: '10:30',
      buyerName: 'Lina V.',
      property: 'Harbour Views · 2BR',
      location: 'Dubai Creek Harbour',
      status: 'confirmed',
      preparation: 'Bring service-charge sheet and balcony view photos.',
    },
    {
      id: 'viewing-2',
      time: '13:15',
      buyerName: 'Hassan K.',
      property: 'Sidra Villas · 4BR',
      location: 'Dubai Hills Estate',
      status: 'pending',
      preparation: 'Confirm gate access and driver details by 11:30.',
    },
    {
      id: 'viewing-3',
      time: '16:00',
      buyerName: 'Priya S.',
      property: 'Marina Gate · 1BR',
      location: 'Dubai Marina',
      status: 'confirmed',
      preparation: 'Buyer comparing net yield against JLT alternative.',
    },
    {
      id: 'viewing-4',
      time: '18:30',
      buyerName: 'Sarah M.',
      property: 'Maple · 3BR',
      location: 'Dubai Hills Estate',
      status: 'follow_up',
      preparation: 'Hold slot if buyer answers morning call.',
    },
  ],
  personalMomentum: {
    weekLabel: 'This week',
    focus: 'Protect the two live offer threads and convert villa campaign interest into booked viewings.',
    stats: [
      {
        label: 'Qualified conversations',
        value: '31',
        helper: '+8 vs last week',
        trend: 'up',
      },
      {
        label: 'Viewing conversion',
        value: '28%',
        helper: 'Target is 30%',
        trend: 'flat',
      },
      {
        label: 'Avg first response',
        value: '6m',
        helper: '12m faster than desk avg',
        trend: 'up',
      },
    ],
    streaks: [
      {
        label: 'Fast response days',
        value: '5',
        tone: 'success',
      },
      {
        label: 'Listings with fresh notes',
        value: '12',
        tone: 'brand',
      },
      {
        label: 'Follow-ups overdue',
        value: '3',
        tone: 'warning',
      },
    ],
  },
}
